nameOverride: creche
fullnameOverride: creche

image:
  repository: rg.fr-par.scw.cloud/mairie-agglo-platform/creche
  tag: preprod-latest

replicaCount: 1

ingress:
  host: preprod.creche.satkaar.io

env:
  DEBUG: "False"
  ALLOWED_HOSTS: "preprod.creche.satkaar.io"
  GUNICORN_WORKERS: "2"
  PORT: "8080"

resources:
  requests:
    cpu: 50m
    memory: 192Mi
  limits:
    cpu: 300m
    memory: 384Mi
